CREATE DATABASE SCHOOL

USE SCHOOL

-- TAI KHOAN
CREATE TABLE TAIKHOAN(
	TAIKHOAN VARCHAR(20) NOT NULL,
	MATKHAU VARCHAR(256) NOT NULL,
	ROLE VARCHAR(10)
)
ALTER TABLE TAIKHOAN ADD PRIMARY KEY(TAIKHOAN)

-- NHAN VIEN
CREATE TABLE NHANVIEN(
	IDNV VARCHAR(10) NOT NULL,
	TENNV NVARCHAR(50),
	CMND VARCHAR(20),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(10),
	QUEQUAN NVARCHAR(50),
	DANTOC NVARCHAR(50),
	HOKHAU NVARCHAR(100),
	SDT VARCHAR(12),
	EMAIL VARCHAR(50),
	LINKAVATAR VARCHAR(50),
	TRANGTHAI BIT
)
ALTER TABLE NHANVIEN ADD PRIMARY KEY(IDNV)
-- HOC SINH
CREATE TABLE HOCSINH(
	IDHS VARCHAR(10) NOT NULL,
	TENHS NVARCHAR(50),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(10),
	QUEQUAN NVARCHAR(50),
	DANTOC NVARCHAR(50),
	HOKHAU NVARCHAR(100),
	SDTPHUHUYNH VARCHAR(12),
	LINKAVATAR VARCHAR(50),
	TRANGTHAI BIT
)
ALTER TABLE HOCSINH ADD PRIMARY KEY(IDHS)

-- GIAO VIEN
CREATE TABLE GIAOVIEN(
	IDGV VARCHAR(10) NOT NULL,
	TENGV NVARCHAR(50),
	CMND VARCHAR(20),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(10),
	QUEQUAN NVARCHAR(50),
	DANTOC NVARCHAR(50),
	HOKHAU NVARCHAR(100),
	SDT VARCHAR(12),
	EMAIL VARCHAR(50),
	LINKAVATAR VARCHAR(50),
	TRANGTHAI BIT
)
ALTER TABLE GIAOVIEN ADD PRIMARY KEY(IDGV)

-- NAM HOC
CREATE TABLE NAMHOC(
	IDNAMHOC VARCHAR(10) NOT NULL,
	TENNAMHOC NVARCHAR(50),
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	TRANGTHAI BIT
)

ALTER TABLE NAMHOC ADD PRIMARY KEY(IDNAMHOC)

-- HOC KY
CREATE TABLE HOCKY(
	IDHOCKY VARCHAR(10) NOT NULL,
	IDNAMHOC VARCHAR(10) NOT NULL,
	TENHOCKY NVARCHAR(50),
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	TRANGTHAI BIT
)
ALTER TABLE HOCKY ADD PRIMARY KEY(IDHOCKY)
ALTER TABLE HOCKY ADD FOREIGN KEY(IDNAMHOC) REFERENCES NAMHOC(IDNAMHOC)

-- KHOI
CREATE TABLE KHOI(
	IDKHOI VARCHAR(10) NOT NULL,
	TENKHOI NVARCHAR(50),
)
ALTER TABLE KHOI ADD PRIMARY KEY(IDKHOI)

-- PHONG HOC
CREATE TABLE PHONGHOC(
	IDPHONGHOC VARCHAR(10) NOT NULL,
	TENPHONGHOC NVARCHAR(50),
)
ALTER TABLE PHONGHOC ADD PRIMARY KEY(IDPHONGHOC)

-- LOP
CREATE TABLE LOP(
	IDLOP VARCHAR(10) NOT NULL,
	TENLOP NVARCHAR(50),
	IDKHOI VARCHAR(10),
	IDPHONGHOC VARCHAR(10),
	IDNAMHOC VARCHAR(10)
)
ALTER TABLE LOP ADD PRIMARY KEY(IDLOP)
ALTER TABLE LOP ADD FOREIGN KEY(IDKHOI) REFERENCES KHOI(IDKHOI)
ALTER TABLE LOP ADD FOREIGN KEY(IDPHONGHOC) REFERENCES PHONGHOC(IDPHONGHOC)
ALTER TABLE LOP ADD FOREIGN KEY(IDNAMHOC) REFERENCES NAMHOC(IDNAMHOC)

-- GIAO VIEN CHU NHIEM
CREATE TABLE GVCN(
	IDLOP VARCHAR(10) NOT NULL,
	IDGV VARCHAR(10) NOT NULL,
	IDHOCKY VARCHAR(10) NOT NULL
)
ALTER TABLE GVCN ADD PRIMARY KEY(IDLOP,IDGV,IDHOCKY)
ALTER TABLE GVCN ADD FOREIGN KEY(IDLOP) REFERENCES LOP(IDLOP)
ALTER TABLE GVCN ADD FOREIGN KEY(IDGV) REFERENCES GIAOVIEN(IDGV)
ALTER TABLE GVCN ADD FOREIGN KEY(IDHOCKY) REFERENCES HOCKY(IDHOCKY)

-- HOC SINH - LOP HOC
CREATE TABLE HOCSINH_LOPHOC(
	IDLOP VARCHAR(10) NOT NULL,
	IDHS VARCHAR(10) NOT NULL,
)
ALTER TABLE HOCSINH_LOPHOC ADD PRIMARY KEY(IDLOP,IDHS)
ALTER TABLE HOCSINH_LOPHOC ADD FOREIGN KEY(IDLOP) REFERENCES LOP(IDLOP)
ALTER TABLE HOCSINH_LOPHOC ADD FOREIGN KEY(IDHS) REFERENCES HOCSINH(IDHS)


-- MON HOC
CREATE TABLE MONHOC(
	IDMONHOC VARCHAR(10) NOT NULL,
	TENMONHOC NVARCHAR(50),
)
ALTER TABLE MONHOC ADD PRIMARY KEY(IDMONHOC)

-- KHOI - MON HOC
CREATE TABLE MONHOC_KHOI(
	IDKHOI VARCHAR(10) NOT NULL,
	IDMONHOC VARCHAR(10) NOT NULL,
)
ALTER TABLE MONHOC_KHOI ADD PRIMARY KEY(IDKHOI,IDMONHOC)
ALTER TABLE MONHOC_KHOI ADD FOREIGN KEY(IDKHOI) REFERENCES KHOI(IDKHOI)
ALTER TABLE MONHOC_KHOI ADD FOREIGN KEY(IDMONHOC) REFERENCES MONHOC(IDMONHOC)

-- TIET
CREATE TABLE TIET(
	IDTIET VARCHAR(10) NOT NULL,
	TENTIET NVARCHAR(50)
)
ALTER TABLE TIET ADD PRIMARY KEY(IDTIET)

-- THU
CREATE TABLE THU(
	IDTHU VARCHAR(10) NOT NULL,
	TENTHU NVARCHAR(50)
)
ALTER TABLE THU ADD PRIMARY KEY(IDTHU)

-- TIET-THU
CREATE TABLE THU_TIET(
	IDTHU VARCHAR(10) NOT NULL,
	IDTIET VARCHAR(10) NOT NULL,
)
ALTER TABLE THU_TIET ADD PRIMARY KEY(IDTHU,IDTIET)
ALTER TABLE THU_TIET ADD FOREIGN KEY(IDTIET) REFERENCES TIET(IDTIET)
ALTER TABLE THU_TIET ADD FOREIGN KEY(IDTHU) REFERENCES THU(IDTHU)

-- GIAO VIEN MON HOC
CREATE TABLE GV_MONHOC(
	IDGV VARCHAR(10) NOT NULL,
	IDMONHOC VARCHAR(10) NOT NULL,
	IDHOCKY VARCHAR(10) NOT NULL
)
ALTER TABLE GV_MONHOC ADD PRIMARY KEY(IDGV,IDMONHOC,IDHOCKY)
ALTER TABLE GV_MONHOC ADD FOREIGN KEY(IDGV) REFERENCES GIAOVIEN(IDGV)
ALTER TABLE GV_MONHOC ADD FOREIGN KEY(IDMONHOC) REFERENCES MONHOC(IDMONHOC)
ALTER TABLE GV_MONHOC ADD FOREIGN KEY(IDHOCKY) REFERENCES HOCKY(IDHOCKY)

-- TKB
CREATE TABLE TKB(
	IDMONHOC VARCHAR(10) NOT NULL,
	IDGV VARCHAR(10) NOT NULL,
	IDLOP VARCHAR(10) NOT NULL,
	IDTIET VARCHAR(10) NOT NULL,
	IDTHU VARCHAR(10) NOT NULL,
	IDHOCKY VARCHAR(10) NOT NULL,
)
ALTER TABLE TKB ADD PRIMARY KEY(IDLOP)
ALTER TABLE TKB ADD FOREIGN KEY(IDGV,IDMONHOC,IDHOCKY) REFERENCES GV_MONHOC(IDGV,IDMONHOC,IDHOCKY)
ALTER TABLE TKB ADD FOREIGN KEY(IDTHU,IDTIET) REFERENCES THU_TIET(IDTHU,IDTIET)
ALTER TABLE TKB ADD FOREIGN KEY(IDLOP) REFERENCES LOP(IDLOP)

-- VANG HOC
CREATE TABLE VANGHOC(
	IDHS VARCHAR(10) NOT NULL,
	IDLOP VARCHAR(10) NOT NULL,
	NGAYVANG DATE,
	LYDO NVARCHAR(100)
)
ALTER TABLE VANGHOC ADD PRIMARY KEY(IDLOP,IDHS)
ALTER TABLE VANGHOC ADD FOREIGN KEY(IDLOP,IDHS) REFERENCES HOCSINH_LOPHOC(IDLOP,IDHS)

-- THONG BAO
CREATE TABLE THONGBAO(
	IDTHONGBAO VARCHAR(10) NOT NULL,
	TITLE NVARCHAR(100),
	CONTENT NVARCHAR(500),
	NGAYDANG DATE
)
ALTER TABLE THONGBAO ADD PRIMARY KEY(IDTHONGBAO)

-- LOAI DIEM
CREATE TABLE LOAIDIEM(
	IDLOAIDIEM VARCHAR(10) NOT NULL,
	TENLOAIDIEM NVARCHAR(100),
	HESO INT CHECK(HESO = 1 OR HESO = 2 OR HESO = 3),
)
ALTER TABLE LOAIDIEM ADD PRIMARY KEY(IDLOAIDIEM)

-- DIEM CUA HOC SINH
CREATE TABLE DIEM(
	IDLOAIDIEM VARCHAR(10) NOT NULL,
	IDHS VARCHAR(10) NOT NULL,
	IDMONHOC VARCHAR(10) NOT NULL,
	DIEM FLOAT NOT NULL,
	IDHOCKY VARCHAR(10) NOT NULL
)
ALTER TABLE DIEM ADD FOREIGN KEY(IDLOAIDIEM) REFERENCES LOAIDIEM(IDLOAIDIEM)
ALTER TABLE DIEM ADD FOREIGN KEY(IDHS) REFERENCES HOCSINH(IDHS)
ALTER TABLE DIEM ADD FOREIGN KEY(IDMONHOC) REFERENCES MONHOC(IDMONHOC)
ALTER TABLE DIEM ADD FOREIGN KEY(IDHOCKY) REFERENCES HOCKY(IDHOCKY)

-- HOC LUC
CREATE TABLE HOCLUC(
	IDHOCLUC VARCHAR(10) NOT NULL,
	TENHOCLUC NVARCHAR(100)
)
ALTER TABLE HOCLUC ADD PRIMARY KEY(IDHOCLUC)

-- HANH KIEM
CREATE TABLE HANHKIEM(
	IDHANHKIEM VARCHAR(10) NOT NULL,
	TENHANHKIEM NVARCHAR(100)
)
ALTER TABLE HANHKIEM ADD PRIMARY KEY(IDHANHKIEM)

-- DANH GIA HS
CREATE TABLE DANHGIA(
	IDHS VARCHAR(10) NOT NULL,
	IDHOCLUC VARCHAR(10) NOT NULL,
	IDHANHKIEM VARCHAR(10) NOT NULL,
	IDHOCKY VARCHAR(10) NOT NULL
)
ALTER TABLE DANHGIA ADD PRIMARY KEY(IDHS,IDHOCKY)
ALTER TABLE DANHGIA ADD FOREIGN KEY(IDHS) REFERENCES HOCSINH(IDHS)
ALTER TABLE DANHGIA ADD FOREIGN KEY(IDHOCKY) REFERENCES HOCKY(IDHOCKY)
ALTER TABLE DANHGIA ADD FOREIGN KEY(IDHOCLUC) REFERENCES HOCLUC(IDHOCLUC)
ALTER TABLE DANHGIA ADD FOREIGN KEY(IDHANHKIEM) REFERENCES HANHKIEM(IDHANHKIEM)
